repos:
  - repo: local
    hooks:
      - id: php-lint
        name: PHP Syntax Check
        entry: php -l
        language: system
        types: [php]

      # - id: php-header-stamp
      #   name: PHP Header Stamp
      #   entry: php vendor/bin/header-stamp --license=agpl.txt --exclude=vendor,tests,_dev
      #   language: system
      #   types: [php]

      - id: php-cs-fixer
        name: PHP-CS-Fixer
        entry: php vendor/bin/php-cs-fixer fix --diff --config=.php-cs-fixer.dist.php
        language: system
        types: [php]

      # - id: phpstan
      #   name: PHPStan
      #   entry: _PS_ROOT_DIR_=/var/www/html vendor/bin/phpstan analyse --no-progress --configuration=tests/phpstan/phpstan.neon
      #   language: system
      #   pass_filenames: false
